/**
 * Cross-language wire-compatibility vectors.
 *
 * fixtures-python-vectors.json was generated by the real Python newton-auth
 * SDK and is the same file newton-auth-nodejs tests against. If this SDK can
 * decrypt and verify these frozen artifacts and recover the exact payloads, it
 * is byte-for-byte compatible with the Python, Go and Node SDKs and with the
 * Newton server's assertions, independent of any live installation.
 */
import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"
import { parseSessionCookieValue, parseStateCookieValue } from "../src/cookies.js"
import { decryptCallbackAssertion, decryptValue, verifySignedValue } from "../src/crypto.js"

interface Vectors {
  clientId: string
  callbackSecret: string
  signingSecret: string
  issuer: string
  assertion: { wire: string; expected: Record<string, unknown> }
  session: { wire: string; expected: Record<string, unknown> }
  state: { wire: string; expected: Record<string, unknown> }
  plain: { object: Record<string, unknown>; encrypted: string; signed: string }
}

const vectors: Vectors = JSON.parse(
  readFileSync(new URL("./fixtures-python-vectors.json", import.meta.url), "utf8"),
)

describe("python-generated wire vectors", () => {
  it("decrypts and validates the callback assertion", async () => {
    const assertion = await decryptCallbackAssertion(
      vectors.assertion.wire,
      vectors.callbackSecret,
      vectors.clientId,
      vectors.issuer,
    )
    expect(assertion).toEqual(vectors.assertion.expected)
  })

  it("decrypts and validates the session cookie", async () => {
    const session = await parseSessionCookieValue(vectors.session.wire, vectors.signingSecret, vectors.clientId)
    expect(session).toEqual(vectors.session.expected)
  })

  it("verifies and validates the state cookie", async () => {
    const state = await parseStateCookieValue(vectors.state.wire, vectors.signingSecret)
    expect(state).toEqual(vectors.state.expected)
  })

  it("round-trips plain encrypted and signed values", async () => {
    expect(await decryptValue(vectors.plain.encrypted, vectors.signingSecret, new Uint8Array(0))).toEqual(
      vectors.plain.object,
    )
    expect(await verifySignedValue(vectors.plain.signed, vectors.signingSecret)).toEqual(vectors.plain.object)
  })
})
